spring:
    profiles: prod

environment: prod
name: Production
url: localhost
port: 8080

mongo:
    clusterHost: ${DB_HOST}
    port: ${DB_PORT}
    dbName: ${DB_NAME}
    auth: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    
file:
  vacciniBaseUrl: https://raw.githubusercontent.com/italia/covid19-opendata-vaccini/master/dati/
  vacciniSummaryFilename: vaccini-summary-latest.csv
  anagraficaVacciniSummaryFilename: anagrafica-vaccini-summary-latest.csv
  puntiSomministrazioneFilename: punti-somministrazione-latest.csv