spring:
    profiles: prod

environment: prod
name: Production
url: localhost
port: 8080

mongo:
    clusterHost: ${DB_HOST}
    port: ${DB_PORT}
    dbName: ${DB_NAME}
    auth: true
    user: ${DB_USER}
    password: ${DB_PASSWORD}